java_test(
    name = "FileSystemBasedSourceFileLoaderTest",
    srcs = ["FileSystemBasedSourceFileLoaderTest.java"],
    deps = [
        "//src/main/java/org/nullable/papyrology/source/file",
        "//src/main/third_party:guava",
        "//src/main/third_party:jimfs",
        "//src/main/third_party:junit",
        "//src/main/third_party:truth",
    ],
)
