package(default_visibility = ["//visibility:public"])

java_library(
    name = "common",
    srcs = glob(["*.java"]),
    deps = [
      "//src/main/third_party:antlr",
      "//src/main/third_party:autovalue",
      "//src/main/third_party:autovalue_annotations",
      "//src/main/third_party:guava",
      "//src/main/third_party:errorprone",
    ],
)
