package(default_visibility = ["//visibility:public"])

java_library(
    name = "file",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/third_party:autovalue",
        "//src/main/third_party:autovalue_annotations",
        "//src/main/third_party:errorprone",
        "//src/main/third_party:guava",
    ],
)
