package(default_visibility = ["//visibility:public"])

java_library(
    name = "analysis",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/org/nullable/papyrology/ast",
        "//src/main/java/org/nullable/papyrology/source",
        "//src/main/third_party:autovalue",
        "//src/main/third_party:autovalue_annotations",
        "//src/main/third_party:errorprone",
        "//src/main/third_party:guava",
    ],
)
