package(default_visibility = ["//visibility:public"])

java_library(
    name = "ast",
    srcs = glob(["*.java"]),
    deps = [
      "//src/main/java/org/nullable/papyrology/ast/node",
      "//src/main/java/org/nullable/papyrology/grammar",
      "//src/main/third_party:antlr",
      "//src/main/third_party:guava",
    ],
)
