package(default_visibility = ["//visibility:public"])

java_library(
    name = "source",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/third_party:antlr",
        "//src/main/third_party:errorprone",
    ],
)
