java_test(
    name = "ScriptFactoryTest",
    srcs = ["ScriptFactoryTest.java"],
    data = [
        "//src/test/scripts",
    ],
    jvm_flags = ["--enable-preview"],
    deps = [
        "//src/main/java/org/nullable/papyrology/ast",
        "//src/main/java/org/nullable/papyrology/grammar",
        "//src/main/third_party:antlr",
        "//src/main/third_party:guava",
        "//src/main/third_party:junit",
        "//src/main/third_party:truth",
    ],
)
