java_test(
    name = "ScriptVisitorTest",
    srcs = ["ScriptVisitorTest.java"],
    data = [
        "//src/test/scripts",
    ],
    deps = [
        "//src/main/java/org/nullable/papyrology/ast",
        "//src/main/java/org/nullable/papyrology/grammar",
        "//src/main/java/org/nullable/papyrology/ast/node",
        "//src/main/third_party:antlr",
        "//src/main/third_party:guava",
        "//src/main/third_party:junit",
        "//src/main/third_party:truth",
    ],
)
