java_test(
    name = "GrammarTest",
    srcs = ["GrammarTest.java"],
    data = [
        "//src/test/scripts",
    ],
    deps = [
        "//src/main/papyrology:papyrus",
        "//src/main/third_party:antlr",
        "//src/main/third_party:guava",
        "//src/main/third_party:junit",
        "//src/main/third_party:truth",
    ],
)
